# Generated by Django 5.2.1 on 2025-08-14 01:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='ユーザー名は英数字のみで構成してください', regex='^[a-zA-Z0-9]+$')]),
        ),
    ]
