# Generated by Django 5.2.1 on 2025-08-27 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0004_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
