# Generated by Django 5.2.1 on 2025-08-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0005_remove_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='memo',
            field=models.TextField(default=''),
        ),
    ]
