# Generated by Django 5.2.1 on 2025-09-03 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0008_post_create_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='create',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
