# Generated by Django 5.2.1 on 2025-09-04 02:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0009_remove_post_create_remove_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default=1, max_length=30, unique=True, verbose_name='表示名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='ユーザー名は@から始まり、英数字・アンダースコアのみ使えます', regex='^@[\\w]+$')]),
        ),
    ]
