# Generated by Django 5.2.1 on 2025-09-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0011_post_created_at_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(max_length=30, verbose_name='表示名'),
        ),
    ]
