# Generated by Django 5.2.1 on 2025-09-11 06:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0013_rename_memo_post_content_post_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=30, verbose_name='表示名')),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('introduce_content', models.TextField(default='')),
                ('place', models.CharField(max_length=20, null=True)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth_date')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
