# Generated by Django 5.2.1 on 2025-09-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0014_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dummy',
            field=models.CharField(default='', max_length=10),
        ),
    ]
