# Generated by Django 5.2.1 on 2025-09-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0017_remove_profile_display_name_remove_profile_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dummy',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
