# Generated by Django 5.2.1 on 2025-09-16 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0018_profile_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dummy',
        ),
    ]
